/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        primary: {
          DEFAULT: '#e8699a',
          50:  '#fef0f5',
          100: '#fdd9e8',
          200: '#fbb3d2',
          300: '#f78cba',
          400: '#f066a2',
          500: '#e8699a',
          600: '#d44f82',
          700: '#b83a6b',
          800: '#962e57',
          900: '#7a2548',
        },
        rose: {
          blush: '#f9e4ee',
          soft:  '#fdf2f7',
          pale:  '#fff5f9',
        },
        sage: {
          DEFAULT: '#8fbc8b',
          50:  '#f2f8f1',
          100: '#e2f1e0',
          200: '#c3e2bf',
          300: '#a3d39e',
          400: '#8fbc8b',
          500: '#6fa66a',
        },
        cream: {
          DEFAULT: '#fef9f0',
          100: '#fef9f0',
          200: '#fdf0dc',
          300: '#fae5c3',
        },
        gold: '#c9a96e',
        charcoal: '#2d2d35',
      },
      fontFamily: {
        sans:    ['Inter', 'sans-serif'],
        heading: ['"Playfair Display"', 'Georgia', 'serif'],
        accent:  ['Cormorant Garamond', 'serif'],
      },
      animation: {
        'fade-in':       'fadeIn 0.6s ease-out both',
        'fade-up':       'fadeUp 0.7s ease-out both',
        'fade-down':     'fadeDown 0.6s ease-out both',
        'slide-right':   'slideRight 0.6s ease-out both',
        'slide-left':    'slideLeft 0.6s ease-out both',
        'scale-in':      'scaleIn 0.4s ease-out both',
        'pulse-soft':    'pulseSoft 3s ease-in-out infinite',
        'float':         'float 4s ease-in-out infinite',
        'shimmer':       'shimmer 2s linear infinite',
        'spin-slow':     'spin 8s linear infinite',
        'bounce-soft':   'bounceSoft 2s ease-in-out infinite',
      },
      keyframes: {
        fadeIn:     { '0%': { opacity: '0' }, '100%': { opacity: '1' } },
        fadeUp:     { '0%': { opacity: '0', transform: 'translateY(24px)' }, '100%': { opacity: '1', transform: 'translateY(0)' } },
        fadeDown:   { '0%': { opacity: '0', transform: 'translateY(-24px)' }, '100%': { opacity: '1', transform: 'translateY(0)' } },
        slideRight: { '0%': { opacity: '0', transform: 'translateX(-32px)' }, '100%': { opacity: '1', transform: 'translateX(0)' } },
        slideLeft:  { '0%': { opacity: '0', transform: 'translateX(32px)' }, '100%': { opacity: '1', transform: 'translateX(0)' } },
        scaleIn:    { '0%': { opacity: '0', transform: 'scale(0.95)' }, '100%': { opacity: '1', transform: 'scale(1)' } },
        pulseSoft:  { '0%,100%': { opacity: '1' }, '50%': { opacity: '0.7' } },
        float:      { '0%,100%': { transform: 'translateY(0)' }, '50%': { transform: 'translateY(-12px)' } },
        shimmer:    { '0%': { backgroundPosition: '-200% 0' }, '100%': { backgroundPosition: '200% 0' } },
        bounceSoft: { '0%,100%': { transform: 'translateY(0)' }, '50%': { transform: 'translateY(-6px)' } },
      },
      boxShadow: {
        'glow':       '0 0 24px rgba(232,105,154,0.25)',
        'glow-lg':    '0 0 48px rgba(232,105,154,0.3)',
        'card':       '0 4px 24px rgba(0,0,0,0.08)',
        'card-hover': '0 12px 40px rgba(0,0,0,0.14)',
        'glass':      '0 8px 32px rgba(31,38,135,0.08)',
        'inner-soft': 'inset 0 2px 8px rgba(0,0,0,0.06)',
      },
      backgroundImage: {
        'gradient-radial':  'radial-gradient(var(--tw-gradient-stops))',
        'gradient-shimmer': 'linear-gradient(90deg, transparent, rgba(255,255,255,0.6), transparent)',
        'hero-pattern':     "url(\"data:image/svg+xml,%3Csvg width='60' height='60' viewBox='0 0 60 60' xmlns='http://www.w3.org/2000/svg'%3E%3Cg fill='none' fill-rule='evenodd'%3E%3Cg fill='%23e8699a' fill-opacity='0.04'%3E%3Ccircle cx='30' cy='30' r='10'/%3E%3C/g%3E%3C/g%3E%3C/svg%3E\")",
      },
      borderRadius: {
        '2xl': '1rem',
        '3xl': '1.5rem',
        '4xl': '2rem',
      },
      transitionDuration: {
        '400': '400ms',
      },
      backdropBlur: {
        xs: '2px',
      },
    },
  },
  plugins: [],
  darkMode: 'class',
};
